name: HiddenKillers
version: 1.0.0
main: com.deejay.projectanonymous.ProjectAnonymous
api-version: 1.20
author: deejay

depend:
  - NickAPI

commands:
  reveal:
    description: Reveal a player for a duration
    usage: /reveal <player> <durationSeconds>
    permission: projectanonymous.reveal

permissions:
  projectanonymous.reveal:
    description: Allows revealing players manually
    default: op
