name: HiddenKillers
version: 1.0.0
main: com.deejay.projectanonymous.ProjectAnonymous
api-version: 1.20
author: deejay

depend:
  - NickAPI

commands:
  reveal:
    description: Reveal a player for a duration
    usage: /reveal <player> <durationSeconds>
    permission: projectanonymous.reveal

  unreveal:
    description: Remove reveal from a player
    usage: /unreveal <player>
    permission: projectanonymous.unreveal

  givecompass:
    description: Give a detective compass
    usage: /givecompass <player>
    permission: projectanonymous.givecompass

  givebell:
    description: Give the Bell of Truth
    usage: /givebell <player>
    permission: projectanonymous.givebell

permissions:
  projectanonymous.reveal:
    description: Allows revealing players manually
    default: op

  projectanonymous.unreveal:
    description: Allows unrevealing players manually
    default: op

  projectanonymous.givecompass:
    description: Allows giving the detective compass
    default: op

  projectanonymous.givebell:
    description: Allows giving the Bell of Truth
    default: op
